#!/usr/bin/env python3
"""
Sync script: Generates MASTER_COACHING_SCHEDULE.md from dashboard CALLS data.

Run this whenever you update the schedule in coaching_dashboard.py:
    python sync_schedule.py

The markdown file is auto-generated - DO NOT edit it directly.
"""

import re
from datetime import date, timedelta
from collections import defaultdict

# Import CALLS and STUDENTS from dashboard
from coaching_dashboard import SCHEDULE, STUDENTS

def get_week_start(d):
    """Get Monday of the week containing date d."""
    days_since_monday = d.weekday()
    return d - timedelta(days=days_since_monday)

def generate_schedule_markdown():
    # Group calls by week
    weeks = defaultdict(list)

    for call in SCHEDULE:
        call_date = date(*call['date'])
        week_start = get_week_start(call_date)
        weeks[week_start].append({
            'date': call_date,
            'time': call['time'],
            'student': call['student'],
            'week': call['week'],
            'course': STUDENTS.get(call['student'], {}).get('course', 'Unknown'),
            'tier': STUDENTS.get(call['student'], {}).get('tier', 'Unknown')
        })

    # Sort weeks and calls within weeks
    sorted_weeks = sorted(weeks.keys())
    for week in sorted_weeks:
        weeks[week].sort(key=lambda x: (x['date'], x['time']))

    # Generate markdown
    lines = [
        "# Master Coaching Schedule - March/April 2026",
        "",
        "> **AUTO-GENERATED** - Do not edit this file directly.",
        "> Source of truth: `SCHEDULE` in `coaching_dashboard.py`",
        "> To update: Edit the dashboard, then run `python sync_schedule.py`",
        "",
        "---",
        ""
    ]

    day_names = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    month_names = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                   'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

    # Check for spring break week (Apr 20-24, 2026)
    spring_break_start = date(2026, 4, 20)
    spring_break_week = get_week_start(spring_break_start)

    for week_start in sorted_weeks:
        # Week header
        month = month_names[week_start.month]
        lines.append(f"## Week of {month} {week_start.day}")

        if week_start == spring_break_week:
            lines.append("*No coaching calls scheduled - SPRING BREAK*")
            lines.append("")
            continue

        lines.append("| Day | Time | Student | Course | Tier |")
        lines.append("|-----|------|---------|--------|------|")

        for call in weeks[week_start]:
            day_name = day_names[call['date'].weekday()]
            month_name = month_names[call['date'].month]
            day_str = f"{day_name} {month_name} {call['date'].day}"

            # Shorten course names
            course = call['course']
            if 'Human Geography' in course:
                course = 'APHG'
            elif 'World History' in course:
                course = 'World'
            elif 'US History' in course:
                course = 'APUSH'
            elif 'Government' in course:
                course = 'Gov'
            elif 'Psychology' in course:
                course = 'Psych'

            lines.append(f"| {day_str} | {call['time']} | {call['student']} | {course} | {call['tier']} |")

        lines.append("")

    # Add spring break if not already included
    if spring_break_week not in sorted_weeks:
        lines.append("## Week of Apr 20 - SPRING BREAK")
        lines.append("*No coaching calls scheduled*")
        lines.append("")

    # Summary section
    lines.extend([
        "---",
        "",
        "## Summary by Tier",
        "",
        "| Tier | Students | Total Calls |",
        "|------|----------|-------------|"
    ])

    # Count by tier
    tier_counts = defaultdict(lambda: {'students': set(), 'calls': 0})
    for call in SCHEDULE:
        tier = STUDENTS.get(call['student'], {}).get('tier', 'Unknown')
        tier_counts[tier]['students'].add(call['student'])
        tier_counts[tier]['calls'] += 1

    tier_order = ['Critical', 'Intensive', 'Moderate', 'Light', 'Maintenance']
    for tier in tier_order:
        if tier in tier_counts:
            students = ', '.join(sorted(tier_counts[tier]['students']))
            if len(students) > 40:
                students = f"{len(tier_counts[tier]['students'])} students"
            lines.append(f"| {tier} | {students} | {tier_counts[tier]['calls']} |")

    total_calls = sum(tc['calls'] for tc in tier_counts.values())
    lines.append(f"| **Total** | **{len(STUDENTS)}** | **{total_calls}** |")

    lines.extend([
        "",
        "---",
        "",
        "## Exam Dates",
        "- **May 5:** AP Human Geography",
        "- **May 7:** AP World History: Modern",
        "- **May 8:** AP US History",
        "- **May 11:** AP US Government",
        ""
    ])

    return '\n'.join(lines)

def main():
    markdown = generate_schedule_markdown()

    output_path = 'student_plans_v3/MASTER_COACHING_SCHEDULE.md'
    with open(output_path, 'w') as f:
        f.write(markdown)

    print(f"Schedule synced to {output_path}")
    print(f"  Total calls: {len(SCHEDULE)}")

if __name__ == '__main__':
    main()
